<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CHI-CL-6RJGL13" name="Karate.KarateScripts.APIRunnerTest" tests="1" failures="1" timestamp="2021-09-27T16:47:03 IST" time="657.039" errors="0">
  <testcase name="parallelRun" time="657.039" classname="Karate.KarateScripts.APIRunnerTest">
    <failure type="java.lang.AssertionError" message="failed features:
resources.Soap: Soap.feature:108 - status code was: 500, expected: 200, response time: 1435, url: https://soap.tracking.thermoking.com/tk-webservices/Command, response: &lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;SOAP-ENV:Header xmlns:SOAP-ENV=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;/&gt;&lt;soap:Body&gt;&lt;soap:Fault&gt;&lt;faultcode&gt;soap:Server&lt;/faultcode&gt;&lt;faultstring&gt;class com.celtrak.webservices.jbossws.service.exceptions.HasGuardedAlaramsException nor any of its super class is known to this context.&lt;/faultstring&gt;&lt;detail&gt;&lt;ns1:Exception xmlns:ns1=&quot;http://service.jbossws.webservices.celtrak.com/&quot;/&gt;&lt;/detail&gt;&lt;/soap:Fault&gt;&lt;/soap:Body&gt;&lt;/soap:Envelope&gt;
Soap.feature:313 - status code was: 500, expected: 200, response time: 962, url: https://soap.tracking.thermoking.com/tk-webservices/Command, response: &lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;SOAP-ENV:Header xmlns:SOAP-ENV=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;/&gt;&lt;soap:Body&gt;&lt;soap:Fault&gt;&lt;faultcode&gt;soap:Server&lt;/faultcode&gt;&lt;faultstring&gt;class com.celtrak.webservices.jbossws.service.exceptions.ProfileNotOnControllerException nor any of its super class is known to this context.&lt;/faultstring&gt;&lt;detail&gt;&lt;ns1:Exception xmlns:ns1=&quot;http://service.jbossws.webservices.celtrak.com/&quot;/&gt;&lt;/detail&gt;&lt;/soap:Fault&gt;&lt;/soap:Body&gt;&lt;/soap:Envelope&gt;
Soap.feature:345 - status code was: 500, expected: 200, response time: 888, url: https://soap.tracking.thermoking.com/tk-webservices/Command, response: &lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;&lt;SOAP-ENV:Header xmlns:SOAP-ENV=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;/&gt;&lt;soap:Body&gt;&lt;soap:Fault&gt;&lt;faultcode&gt;soap:Server&lt;/faultcode&gt;&lt;faultstring&gt;Fault occurred while processing.&lt;/faultstring&gt;&lt;detail&gt;&lt;ns1:Exception xmlns:ns1=&quot;http://service.jbossws.webservices.celtrak.com/&quot;/&gt;&lt;/detail&gt;&lt;/soap:Fault&gt;&lt;/soap:Body&gt;&lt;/soap:Envelope&gt;
Soap.feature:374 - path: /Envelope/Body/viewDoorAlarmResponse/requestReference/status, actual: &#039;false&#039;, expected: &#039;true&#039;, reason: not equal
">
      <![CDATA[java.lang.AssertionError: failed features:
resources.Soap: Soap.feature:108 - status code was: 500, expected: 200, response time: 1435, url: https://soap.tracking.thermoking.com/tk-webservices/Command, response: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"/><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>class com.celtrak.webservices.jbossws.service.exceptions.HasGuardedAlaramsException nor any of its super class is known to this context.</faultstring><detail><ns1:Exception xmlns:ns1="http://service.jbossws.webservices.celtrak.com/"/></detail></soap:Fault></soap:Body></soap:Envelope>
Soap.feature:313 - status code was: 500, expected: 200, response time: 962, url: https://soap.tracking.thermoking.com/tk-webservices/Command, response: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"/><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>class com.celtrak.webservices.jbossws.service.exceptions.ProfileNotOnControllerException nor any of its super class is known to this context.</faultstring><detail><ns1:Exception xmlns:ns1="http://service.jbossws.webservices.celtrak.com/"/></detail></soap:Fault></soap:Body></soap:Envelope>
Soap.feature:345 - status code was: 500, expected: 200, response time: 888, url: https://soap.tracking.thermoking.com/tk-webservices/Command, response: <soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"/><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>Fault occurred while processing.</faultstring><detail><ns1:Exception xmlns:ns1="http://service.jbossws.webservices.celtrak.com/"/></detail></soap:Fault></soap:Body></soap:Envelope>
Soap.feature:374 - path: /Envelope/Body/viewDoorAlarmResponse/requestReference/status, actual: 'false', expected: 'true', reason: not equal

at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.assertTrue(Assert.java:41)
at Karate.KarateScripts.APIRunnerTest.parallelRun(APIRunnerTest.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- parallelRun -->
  <system-out/>
</testsuite> <!-- Karate.KarateScripts.APIRunnerTest -->
